name: Publish





on:
  push:
    tags:
      - vt/*





jobs:

  Publishing:
    name: Publish
    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - run: npm install
        env:
          ADBLOCK: true
          DISABLE_OPENCOLLECTIVE: true
          HUSKY_SKIP_INSTALL: true

      - name: Build china-list
        run: sh ci.sh ./ gen_china_list

      - run: npm publish --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: curl -sLo /dev/null https://npm.taobao.org/sync/$(jq -r '.name' package.json) &

